import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img></img>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-me">About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href="">
          <img></img>
          <h2>events in london</h2>
          <p>lorem ipsum dolor sit amet</p>
        </a>
        <a href="">
          <img></img>
          <h2>events in paris</h2>
          <p>lorem ipsum dolor sit amet</p>
        </a>
        <a href="">
          <img></img>
          <h2>events in germany</h2>
          <p>lorem ipsum dolor sit amet</p>
        </a>
      </main>

      <footer>
        <p>Bu bir deneme footer yazısıdır.</p>
      </footer>
    </>
  );
}
