import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Nextjs Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img></img>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-me">About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((e) => (
          <a key={e.id} href={`/events/${e.id}`}>
            <img width={700} height={"100%"} src={e.image}></img>
            <h2>{e.title}</h2>
            <p>{e.description}</p>
          </a>
        ))}
      </main>

      <footer>
        <p>Bu bir deneme footer yazısıdır.</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
